apiVersion: v1
kind: Service

# the service description

metadata:
  name: charon-backend
  labels:
    app: charon-backend

spec:
  type: { { .Values.service.type } }
  selector:
    app: charon-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8888
      nodePort: 30036
