get:
  tags:
    - configurationDetails
  operationId: readClientConfigurationList
  description: ''
  responses:
    '200':
      description: successful operation
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: "../model/ClientConfiguration.yaml"

    '405':
      description: Invalid input
