get:
  tags:
    - configurationDetails
  operationId: readConfigurationDetails
  description: ''
  responses:
    '200':
      description: successful operation
      content:
        application/json:
          schema:
            $ref: "../model/ConfigurationDetails.yaml"
    '405':
      description: Invalid input
