post:
  tags:
    - loggingBackend
  operationId: postLogRecord
  description: ''
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: "../model/LogEntry.yaml"
  responses:
    200:
      description: "200 response"
