
[![CI](https://github.com/mwohlf/charon/actions/workflows/gradle-build.yml/badge.svg?branch=master)](https://github.com/mwohlf/charon/actions/workflows/gradle-build.yml)


== authService

This module implements an OAuth Service with with the spring-security-oauth2-authorization-server SpringBoot module.

see: https://github.com/spring-projects/spring-authorization-server/blob/main/samples/federated-identity-authorizationserver/src/main/resources/application.yml
for provider config

=== info endpoint

http://localhost:8081/.well-known/openid-configuration


== backend

SpringBoot endpoints in Kotlin and hosting the webjar at

http://localhost:8080/charon/index.html


== frontend

Angular Frontend

setup:

  ng update @angular/core @angular/cli
  ng generate component components/home
  ng generate component components/main
  ng generate component components/error
  ng generate component components/protected
  ng add @angular/material
  ng add @angular/cdk
  ng generate @angular/material:navigation navigation

for debugging:

  ng serve

oauth from here:
https://github.com/damienbod/angular-auth-oidc-client
with:
npm install angular-auth-oidc-client --registry https://registry.npmjs.org --legacy-peer-deps

to update angular:
ng update @angular/core @angular/cli


