
= Charon
:toc:

image::https://github.com/mwohlf/charon/actions/workflows/gradle-build.yml/badge.svg?[https://github.com/mwohlf/charon/actions/workflows/gradle-build.yml]


== intro

This is a POC for implementing an OAuth Server and an Angular UI using it, in mostly  Kotlin/Typescript, basically showing off:

 - a fancy buildSrc with re-usable custom plugins
 - using webjars to integrate the UI with the Spring boot service
 - using Kotlin for implementing spring-boot backends
 - material Angular with theme switching and OAuth for authentication
 - using OpenAPI for "API-first" code generation for
    ** the backend (controllers)
    ** the frontend (services)
 - using GitHub's actions and build pipeline
 - a fancy deployment in azure

I think this is today's state-of-the-art web application development



== oauth module

This module implements an OAuth Service and is based on the
  spring-security-oauth2-authorization-server
SpringBoot module.

We want to use the OAuth Code Flow for authentication.

Documentation can be found here: +
https://developer.okta.com/blog/2018/04/10/oauth-authorization-code-grant-type[Okta Code GRant Docu] +
https://docs.spring.io/spring-authorization-server/docs/current/reference/html/getting-started.html[Spring OAuth Server Howto] +
https://github.com/spring-projects/spring-authorization-server[GitHub Spring AOuth Server] +
https://github.com/spring-projects/spring-authorization-server/blob/main/samples/federated-identity-authorizationserver/src/main/resources/application.yml[Federated OAuth Server Config] +
https://stackoverflow.com/questions/71479250/spring-security-oauth2-authorization-server-angular-auth-oidc-client[Stackoverflow Spring OAuth Server] +
https://github.com/sjohnr/spring-authorization-server/tree/bff-demo/samples/default-authorizationserver/src[GitHub OAuth Server POC] +

Some OAuth Endpoints provided by the Server
|===
|URL | service

| http://localhost:9000/.well-known/openid-configuration
| issuer config endpoint

| http://localhost:9000/.well-known/oauth-authorization-server
| server config endpoint
|===


== frontend module

This module implements a simple UI using the OAuth backend for authentication. +
Setup steps: +

  npm i
  ng update @angular/core
  ng update @angular/cli
  ng generate component components/home
  ng generate component components/main
  ng generate component components/error
  ng generate component components/protected
  ng add @angular/material
  ng add @angular/cdk
  ng generate @angular/material:navigation navigation
  npm install angular-auth-oidc-client --registry https://registry.npmjs.org --legacy-peer-deps

oauth module from here: +
https://github.com/damienbod/angular-auth-oidc-client +
https://angular-auth-oidc-client.com/docs/documentation/public-api +

proxy service config: +
https://angular.io/guide/build#proxying-to-a-backend-server


=== simple ngrx concepts

Actions::
Describe unique events, dispatched from Components (Users), Services (Backends) and might contain data.

Reducer::
Convert action types, the data from actions and the current state into a new State.

Effects::
Listen to an observable of every action dispatched from the store, interact with Services, Isolate side effects, **return new actions**. Also include state (e.g. with
withLatestFrom(this.store.select(selectOAuthFeature)) ) to create a new action.


Components::
Select and render state, dispatch actions.


=== simple commands

update dependencies::

npm run ncu

build::

npm install --legacy-peer-deps


== backend module

SpringBoot endpoints in Kotlin and hosting the webjar at

http://localhost:8080/charon/index.html



== buildSrc module

This contains the custom, re-usable build scripts for
kotlin & spring-boot, angular, docker etc.

The only requirement is having git, java and docker in the build environment,
for ubuntu this means:

  sudo apt-get install \
    git \
    openjdk-17-jdk \
    docker \

== .github

the GitHub pipelines or workflows

* aks-deploy.yml +
  trigger a helm chart deploy from the etc/helm directory

* gradle-build.yml +
  trigger the gradle jib build for creating the images configured by the buildSrc

== etc

contains API definition, scripts, deployment descriptions, helm charts

'''

For now, we are pushing the images to an ephemeral docker image registry at:
https://ttl.sh/mwohlf/charon-backend +

Simple boot up the backend image:

  docker run -p 8080:8080 ttl.sh/mwohlf/charon-backend
  docker run -p 8080:8080 ttl.sh/mwohlf/charon-backend:72716232cce3e4b1bfec01379cae6cbf5f269725
  docker run -p 8081:8081 ttl.sh/mwohlf/charon-oauth:72716232cce3e4b1bfec01379cae6cbf5f269725

Deployment is outlined here: +
https://www.koslib.com/posts/deploy-k8s-apps-helm-complete/ +
https://github.com/Azure/actions-workflow-samples +

The `etc/setup/azure.bash` script can be used to perform:

[source]
----
 - create: to setup up the cluster
 - deploy_dashboard: to show the k8s dashboard
 - deploy_chart: to deploy the helm chart
 - delete_chart: to delete the helm chart
 - login_azure: to login for local az, not needed in azure cloud cli
 - create_public_ip_address: create an ip address
 - delete: to remove the cluster
----


todo: +
https://bhuwanupadhyay.github.io/2020/06/expose-spring-boot-microservice-with-ingress-using-helm/ +
https://unbroken-dome.github.io/projects/gradle-helm-plugin/latest/userguide/index.html +


-

=== deployment steps

- remove old namespace with cluster and all the configs +
`./azure.bash delete`

- create cluster, namespace, nodepools etc +
`./azure.bash create_cluster`

- update service account +
the content of credentials.txt goes into the GitHub secrets as `AZURE_SP_CREDENTIALS`

- update IP +
`kubectl get service --all-namespaces`  +
shows the current IP which needs to b configured in cloudflare




=== update UI components:

[source]
----
cd frontend
ncu -u
npm install --legacy-peer-deps
----

if UI build fail on GitHub, try deleting the caches and trigger another build

=== deployment troubleshooting

- `kubectl get ingress --all-namespaces`

- `kubectl get pods --all-namespaces`

- `kubectl get deployments --all-namespaces`

- `kubectl get deployments --all-namespaces`

- `kubectl logs charon-backend-deployment-z4zlj --namespace development`



==== Spring Auth Server Project:

https://github.com/spring-projects/spring-authorization-server +
https://www.appsdeveloperblog.com/spring-authorization-server-tutorial/ +
https://github.com/spring-projects/spring-authorization-server/issues/796 +
https://github.com/spring-projects/spring-authorization-server/issues/297 +
https://docs.spring.io/spring-authorization-server/docs/current/reference/html/guides/how-to-userinfo.html +



==== k8s resources

https://labzilla.io/blog/cloudflare-certbot +
https://github.com/spring-projects/spring-authorization-server/pull/335
https://github.com/marketplace/actions/kubernetes-bake


==== running docker without docker desktop

install with choco:

- docker-cli
- docker-compose
- use the WSL context in idea to connect to a docker deamon
- set the path do docker.exe/docker-compose.exe in idea




==== request path

2023-05-11T23:15:43.954+02:00 DEBUG 8052 --- [nio-8081-exec-2] o.s.s.w.s.HttpSessionRequestCache        : Saved request http://127.0.0.1:8081/oauth2/authorize?client_id=public-client&redirect_uri=http%3A%2F%2F127.0.0.1%3A4200%2Fcharon%2Fhome&response_type=code&scope=openid%20profile%20email%20offline_access&nonce=0d4fd3402e2f87933ea6f6f8dcf91c1853suy7LC3&state=17e3ee7dbadb5cc5f1cd6ebd86dde88559M6zafEe&code_challenge=WVGxVZwl3ShzJNvToKTkTVGrI-1UvgOst-29qPS3Wss&code_challenge_method=S256&continue to session
2023-05-11T23:15:43.958+02:00 DEBUG 8052 --- [nio-8081-exec-2] o.s.s.web.DefaultRedirectStrategy        : Redirecting to http://127.0.0.1:8081/login

2023-05-11T23:18:07.191+02:00 DEBUG 8052 --- [io-8081-exec-10] o.s.security.web.FilterChainProxy        : Securing POST /login

2023-05-11T23:18:07.410+02:00 DEBUG 8052 --- [io-8081-exec-10] o.s.s.web.DefaultRedirectStrategy        : Redirecting to http://127.0.0.1:8081/oauth2/authorize?client_id=public-client&redirect_uri=http%3A%2F%2F127.0.0.1%3A4200%2Fcharon%2Fhome&response_type=code&scope=openid%20profile%20email%20offline_access&nonce=0d4fd3402e2f87933ea6f6f8dcf91c1853suy7LC3&state=17e3ee7dbadb5cc5f1cd6ebd86dde88559M6zafEe&code_challenge=WVGxVZwl3ShzJNvToKTkTVGrI-1UvgOst-29qPS3Wss&code_challenge_method=S256&continue

2023-05-11T23:18:07.457+02:00 DEBUG 8052 --- [nio-8081-exec-8] o.s.s.web.DefaultRedirectStrategy        : Redirecting to http://127.0.0.1:4200/charon/home?code=cWq2tSVwYZOc8q09jfUeTH6JpaDzrGslKvZPDxn3wPfKf_17HJPP-xB8IqKFNCbNU1MM9OYZl3uOVwyI_OLZ4S2rPxRl14tIdYcQ4IN0hswvyHpgcDtp2Z8nNvy0ZD5o&state=17e3ee7dbadb5cc5f1cd6ebd86dde88559M6zafEe


2023-05-11T23:18:08.170+02:00 DEBUG 8052 --- [nio-8081-exec-7] o.s.security.web.FilterChainProxy        : Securing GET /oauth2/jwks

2023-05-11T23:18:40.247+02:00 DEBUG 8052 --- [nio-8081-exec-1] o.s.security.web.FilterChainProxy        : Securing GET /oauth2/authorize?client_id=public-client&redirect_uri=http%3A%2F%2F127.0.0.1%3A4200%2Fcharon%2Fassets%2Fsilent-renew.html&response_type=code&scope=openid%20profile%20email%20offline_access&nonce=e23c9d442b091ef894eced41907db015b3J8Fb5DW&state=91b349d8d31b80ac142fe9529b7a5c6e98mbT0v4j&code_challenge=rRhblyCnqAz8vKJCvQsnQfb3KLTgfwn4yZp9zoA6UaA&code_challenge_method=S256&prompt=none


2023-05-11T23:18:40.257+02:00 DEBUG 8052 --- [nio-8081-exec-1] o.s.s.web.DefaultRedirectStrategy        : Redirecting to http://127.0.0.1:4200/charon/assets/silent-renew.html?code=kopW50iJN0YiI4fWstTQkLe4NibVctrsTN253buzhBpRwrNpNy0dTU6jXyIr3_oGucf5ONEvo8rPRW3DWyiqJYVcUICR5Xyg6bpq6iEbZOnoDWKp53NsQyJsRhw18U1L&state=91b349d8d31b80ac142fe9529b7a5c6e98mbT0v4j



===== google client scope config


configure: https://console.cloud.google.com/apis/credentials/consent/edit?project=charon-394311
