
= Charon
:toc:

image::https://github.com/mwohlf/charon/actions/workflows/gradle-build.yml/badge.svg?branch=master[https://github.com/mwohlf/charon/actions/workflows/gradle-build.yml]

== intro

This is a POC for implementing an OAuth Server and an Angular UI using it, in mostly  Kotlin/Typescript, basically showing off:

 - a fancy buildSrc with re-usable custom plugins
 - using webjars to integrate the UI with the Spring boot service
 - using Kotlin for implementing spring-boot backends
 - material Angular with theme switching and OAuth for authentication
 - using OpenAPI for "API-first" code generation for
    ** the backend (controllers)
    ** the frontend (services)
 - using github's actions and build pipeline
 - using

I think this is today's state-of-the-art web application development
and the best approach


== oauth module

This module implements an OAuth Service and is based on the
  spring-security-oauth2-authorization-server
SpringBoot module.

We want to use the OAuth Code Flow for authentication. +

Documentation can be found here: +

https://developer.okta.com/blog/2018/04/10/oauth-authorization-code-grant-type[Okta Code GRant Docu] +
https://docs.spring.io/spring-authorization-server/docs/current/reference/html/getting-started.html[Spring OAuth Server Howto] +
https://github.com/spring-projects/spring-authorization-server[GitHub Spring AOuth Server] +
https://github.com/spring-projects/spring-authorization-server/blob/main/samples/federated-identity-authorizationserver/src/main/resources/application.yml[Federated OAuth Server Config] +
https://stackoverflow.com/questions/71479250/spring-security-oauth2-authorization-server-angular-auth-oidc-client[Stackoverflow Spring OAuth Server] +
https://github.com/sjohnr/spring-authorization-server/tree/bff-demo/samples/default-authorizationserver/src[GitHub OAuth Server POC] +

Some OAuth Endpoints provided by the Server
|===
|URL | service

| http://localhost:9000/.well-known/openid-configuration
| issuer config endpoint

| http://localhost:9000/.well-known/oauth-authorization-server
| server config endpoint
|===


== frontend module

This module implements a simple UI using the OAuth backend for authentication. +
Setup steps: +

  ng update @angular/core @angular/cli
  ng generate component components/home
  ng generate component components/main
  ng generate component components/error
  ng generate component components/protected
  ng add @angular/material
  ng add @angular/cdk
  ng generate @angular/material:navigation navigation
  npm install angular-auth-oidc-client --registry https://registry.npmjs.org --legacy-peer-deps

oauth module from here:
https://github.com/damienbod/angular-auth-oidc-client +

proxy service config:
https://angular.io/guide/build#proxying-to-a-backend-server



== backend module

SpringBoot endpoints in Kotlin and hosting the webjar at

http://localhost:8080/charon/index.html



== buildSrc module

This contains the custom, re-usable build scripts for
kotlin & spring-boot, angular, docker etc.

The only requirement is having git, java and docker in the build environment,
for ubuntu this means:

  sudo apt-get install \
    git \
    openjdk-17-jdk \
    docker \



== etc

contains deployment descriptions,
API definition, scripts


For now we are pushing the images to an ephemeral docker image registry.

see:
https://ttl.sh/
