
= Charon
:toc:

image::https://github.com/mwohlf/charon/actions/workflows/gradle-build.yml/badge.svg?branch=master[https://github.com/mwohlf/charon/actions/workflows/gradle-build.yml]

== intro

This is a POC for implementing an OAuth Server and an Angular UI using it, in mostly  Kotlin/Typescript, basically showing off:

 - a fancy buildSrc with re-usable custom plugins
 - using webjars to integrate the UI with the Spring boot service
 - using Kotlin for implementing spring-boot backends
 - material Angular with theme switching and OAuth for authentication
 - using OpenAPI for "API-first" code generation for
    ** the backend (controllers)
    ** the frontend (services)
 - using github's actions and build pipeline
 - using

I think this is today's state-of-the-art web application development
and the best approach


== oauth module

This module implements an OAuth Service and is based on the
  spring-security-oauth2-authorization-server
SpringBoot module.

We want to use the OAuth Code Flow for authentication.
Documentation can be found here:

https://developer.okta.com/blog/2018/04/10/oauth-authorization-code-grant-type

=== Requests

GET: +
http://localhost:4200/issuer/.well-known/openid-configuration

GET: +
http://localhost:4200/issuer/oauth2/authorize
?client_id=messaging-client
&redirect_uri=http%3A%2F%2Flocalhost%3A4200
&response_type=code
&scope=read
&nonce=91b7886792dbd7422a7e23b9efd13a7605oZVDuuW&state=471baa54212a1c1638821f836337e90378kDszeOw
&code_challenge=tF9X_76O9L0Ifz9xQ-MgPbF3vt4qYzLLWDHsgaYCOZg
&code_challenge_method=S256

returns redirect +
 -> http://localhost:4200/issuer/login

POST:
http://localhost:4200/issuer/login
username=user
&password=pass
&_csrf=52ee8c60-4e9e-4d7c-8292-179a17901065

returns redirect +
-> http://localhost:4200/issuer/error
?client_id=messaging-client
&redirect_uri=http%3A%2F%2Flocalhost%3A4200
&response_type=code
&scope=read
&nonce=91b7886792dbd7422a7e23b9efd13a7605oZVDuuW&state=471baa54212a1c1638821f836337e90378kDszeOw
&code_challenge=tF9X_76O9L0Ifz9xQ-MgPbF3vt4qYzLLWDHsgaYCOZg
&code_challenge_method=S256







---

docs: https://docs.spring.io/spring-authorization-server/docs/current/reference/html/getting-started.html +
repo: https://github.com/spring-projects/spring-authorization-server +
config example:
https://github.com/spring-projects/spring-authorization-server/blob/main/samples/federated-identity-authorizationserver/src/main/resources/application.yml +

|===
|URL | service

| http://localhost:8081/.well-known/openid-configuration
| issuer config endpoint

| http://localhost:8081/.well-known/oauth-authorization-server
| server config endpoint
|===


== frontend module

This module implements a simple UI using the OAuth backend for authentication. +
Setup steps: +

  ng update @angular/core @angular/cli
  ng generate component components/home
  ng generate component components/main
  ng generate component components/error
  ng generate component components/protected
  ng add @angular/material
  ng add @angular/cdk
  ng generate @angular/material:navigation navigation
  npm install angular-auth-oidc-client --registry https://registry.npmjs.org --legacy-peer-deps

oauth from here:
https://github.com/damienbod/angular-auth-oidc-client +

proxy service:
https://angular.io/guide/build#proxying-to-a-backend-server



== backend module

SpringBoot endpoints in Kotlin and hosting the webjar at

http://localhost:8080/charon/index.html



== buildSrc module

This contais the custom, re-usable buil scripts for koting & spring-boot,
angular, docker etc.

The only requirement is having git, java and docker in the build environment,
for ubuntu this means:

  sudo apt-get install \
    git \
    openjdk-17-jdk \
    docker \

We also use ttl.sh an ephemeral docker image registry for deployment

see:
https://ttl.sh/
