
= Charon
:toc:

image::https://github.com/mwohlf/charon/actions/workflows/gradle-build.yml/badge.svg?[https://github.com/mwohlf/charon/actions/workflows/gradle-build.yml]

== TL;DR
```
./gradlew jibDockerBuild
docker run <imageid>
```
== intro

This is a POC for implementing an OAuth Server and an Angular UI using it, in mostly  Kotlin/Typescript, basically showing off:

 - a fancy buildSrc with re-usable custom plugins
 - using webjars to integrate the UI with the Spring boot service
 - using Kotlin for implementing spring-boot backends
 - material Angular with theme switching and OAuth for authentication
 - using OpenAPI for "API-first" code generation for
    ** the backend (controllers)
    ** the frontend (services)
 - using github's actions and build pipeline
 - a fancy deployment in azure

I think this is today's state-of-the-art web application development



== oauth module

This module implements an OAuth Service and is based on the
  spring-security-oauth2-authorization-server
SpringBoot module.

We want to use the OAuth Code Flow for authentication.

Documentation can be found here: +
https://developer.okta.com/blog/2018/04/10/oauth-authorization-code-grant-type[Okta Code GRant Docu] +
https://docs.spring.io/spring-authorization-server/docs/current/reference/html/getting-started.html[Spring OAuth Server Howto] +
https://github.com/spring-projects/spring-authorization-server[GitHub Spring AOuth Server] +
https://github.com/spring-projects/spring-authorization-server/blob/main/samples/federated-identity-authorizationserver/src/main/resources/application.yml[Federated OAuth Server Config] +
https://stackoverflow.com/questions/71479250/spring-security-oauth2-authorization-server-angular-auth-oidc-client[Stackoverflow Spring OAuth Server] +
https://github.com/sjohnr/spring-authorization-server/tree/bff-demo/samples/default-authorizationserver/src[GitHub OAuth Server POC] +

Some OAuth Endpoints provided by the Server
|===
|URL | service

| http://localhost:9000/.well-known/openid-configuration
| issuer config endpoint

| http://localhost:9000/.well-known/oauth-authorization-server
| server config endpoint
|===


== frontend module

This module implements a simple UI using the OAuth backend for authentication. +
Setup steps: +

  npm i
  ng update @angular/core
  ng update @angular/cli
  ng generate component components/home
  ng generate component components/main
  ng generate component components/error
  ng generate component components/protected
  ng add @angular/material
  ng add @angular/cdk
  ng generate @angular/material:navigation navigation
  npm install angular-auth-oidc-client --registry https://registry.npmjs.org --legacy-peer-deps

oauth module from here: +
https://github.com/damienbod/angular-auth-oidc-client +
https://angular-auth-oidc-client.com/docs/documentation/public-api +

proxy service config: +
https://angular.io/guide/build#proxying-to-a-backend-server


=== simple ngrx concepts

Actions:: Describe unique events, dispatched from Components (Users), Services (Backends) and might contain data.

Reducer:: Convert action types, the data from actions and the current state into a new State.

Effects:: Listen to an observable of every action dispatched from the store, interact with Services, Isolate side effects, return new actions.


Components:: Select and render state, dispatch actions.

== backend module

SpringBoot endpoints in Kotlin and hosting the webjar at

http://localhost:8080/charon/index.html



== buildSrc module

This contains the custom, re-usable build scripts for
kotlin & spring-boot, angular, docker etc.

The only requirement is having git, java and docker in the build environment,
for ubuntu this means:

  sudo apt-get install \
    git \
    openjdk-17-jdk \
    docker \

== .github

the github pipelines or workflows

* aks-deploy.yml +
  trigger a helm chart deploy from the etc/helm directory

* gradle-build.yml +
  trigger the gradle jib build for creating the images configured by the buildSrc

== etc

contains API definition, scripts, deployment descriptions, helm charts

'''

For now we are pushing the images to an ephemeral docker image registry at:
https://ttl.sh/mwohlf/charon-backend +

Simple bootup the backend image:

  docker run -p 8080:8080 ttl.sh/mwohlf/charon-backend
  docker run -p 8080:8080 ttl.sh/mwohlf/charon-backend:72716232cce3e4b1bfec01379cae6cbf5f269725
  docker run -p 8081:8081 ttl.sh/mwohlf/charon-oauth:72716232cce3e4b1bfec01379cae6cbf5f269725

Deployment is outlined here: +
https://www.koslib.com/posts/deploy-k8s-apps-helm-complete/ +
https://github.com/Azure/actions-workflow-samples +

The `etc/setup/azure.bash` script can be used to perform:

[source]
----
 - create: to setup up the cluster
 - deploy_dashboard: to show the k8s dashboard
 - deploy_chart: to deploy the helm chart
 - delete_chart: to delete the helm chart
 - login_azure: to login for local az, not needed in azure cloud cli
 - create_public_ip_address: create an ip address
 - delete: to remove the cluster
----


todo: +
https://bhuwanupadhyay.github.io/2020/06/expose-spring-boot-microservice-with-ingress-using-helm/ +
https://unbroken-dome.github.io/projects/gradle-helm-plugin/latest/userguide/index.html +


-

### deployment steps

- remove old namespace with cluster and all the configs +
`./azure.bash delete`

- create cluster, namespace, nodepools etc +
`./azure.bash create_cluster`

- update service account +
the content of credentials.txt goes into the github secrets as `AZURE_SP_CREDENTIALS`

- update IP +
`kubectl get service --all-namespaces`  +
shows the current IP which needs to b configured in cloudflare


### deployment troubleshooting

- kubectl get ingress --all-namespaces

- kubectl get pods --all-namespaces

- kubectl get deployments --all-namespaces

- kubectl get deployments --all-namespaces

- kubectl logs charon-backend-deployment-6996d676b6-z4zlj --namespace development

#### Spring Auth Server Project:

https://github.com/spring-projects/spring-authorization-server +
https://www.appsdeveloperblog.com/spring-authorization-server-tutorial/ +
https://github.com/spring-projects/spring-authorization-server/issues/796 +
https://github.com/spring-projects/spring-authorization-server/issues/297 +
https://docs.spring.io/spring-authorization-server/docs/current/reference/html/guides/how-to-userinfo.html +


#### OAuth Client Project:

angular-auth-oidc-client

https://github.com/damienbod/angular-auth-oidc-client +


#### k8s resources

https://medium.com/google-cloud/kubernetes-nodeport-vs-loadbalancer-vs-ingress-when-should-i-use-what-922f010849e0
https://medium.com/microsoftazure/aks-different-load-balancing-options-for-a-single-cluster-when-to-use-what-abd2c22c2825

https://docs.microsoft.com/en-us/azure/application-gateway/ingress-controller-letsencrypt-certificate-application-gateway

https://techblog.buzyka.de/2021/02/make-lets-encrypt-certificates-love.html

https://gist.github.com/jult/e4dd064e3988aa111ea2194b05bc69f5


https://labzilla.io/blog/cloudflare-certbot

https://github.com/spring-projects/spring-authorization-server/pull/335
