
= Charon
:toc:

image::https://github.com/mwohlf/charon/actions/workflows/gradle-build.yml/badge.svg?[https://github.com/mwohlf/charon/actions/workflows/gradle-build.yml]


== intro

This is a POC for implementing an OAuth Server and an Angular UI using it, in mostly  Kotlin/Typescript, basically showing off:

 - a fancy buildSrc with re-usable custom plugins
 - using webjars to integrate the UI with the Spring boot service
 - using Kotlin for implementing spring-boot backends
 - material Angular with theme switching and OAuth for authentication
 - using OpenAPI for "API-first" code generation for
    ** the backend (controllers)
    ** the frontend (services)
 - using GitHub's actions and build pipeline
 - a fancy deployment in azure

I think this is today's state-of-the-art web application development



== oauth module

This module implements an OAuth Service and is based on the
  spring-security-oauth2-authorization-server
SpringBoot module.

We want to use the OAuth Code Flow for authentication.

Documentation can be found here: +
https://developer.okta.com/blog/2018/04/10/oauth-authorization-code-grant-type[Okta Code GRant Docu] +
https://docs.spring.io/spring-authorization-server/docs/current/reference/html/getting-started.html[Spring OAuth Server Howto] +
https://github.com/spring-projects/spring-authorization-server[GitHub Spring AOuth Server] +
https://github.com/spring-projects/spring-authorization-server/blob/main/samples/federated-identity-authorizationserver/src/main/resources/application.yml[Federated OAuth Server Config] +
https://stackoverflow.com/questions/71479250/spring-security-oauth2-authorization-server-angular-auth-oidc-client[Stackoverflow Spring OAuth Server] +
https://github.com/sjohnr/spring-authorization-server/tree/bff-demo/samples/default-authorizationserver/src[GitHub OAuth Server POC] +

Some OAuth Endpoints provided by the Server
|===
|URL | service

| http://localhost:9000/.well-known/openid-configuration
| issuer config endpoint

| http://localhost:9000/.well-known/oauth-authorization-server
| server config endpoint
|===


== frontend module

This module implements a simple UI using the OAuth backend for authentication. +
Setup steps: +

  npm i
  ng update @angular/core
  ng update @angular/cli
  ng generate component components/home
  ng generate component components/main
  ng generate component components/error
  ng generate component components/protected
  ng add @angular/material
  ng add @angular/cdk
  ng generate @angular/material:navigation navigation
  npm install angular-auth-oidc-client --registry https://registry.npmjs.org --legacy-peer-deps

oauth module from here: +
https://github.com/damienbod/angular-auth-oidc-client +
https://angular-auth-oidc-client.com/docs/documentation/public-api +

proxy service config: +
https://angular.io/guide/build#proxying-to-a-backend-server


=== simple ngrx concepts

Actions::
Describe unique events, dispatched from Components (Users), Services (Backends) and might contain data.

Reducer::
Convert action types, the data from actions and the current state into a new State.

Effects::
Listen to an observable of every action dispatched from the store, interact with Services, Isolate side effects, **return new actions**. Also include state (e.g. with
withLatestFrom(this.store.select(selectOAuthFeature)) ) to create a new action.


Components::
Select and render state, dispatch actions.


== backend module

SpringBoot endpoints in Kotlin and hosting the webjar at

http://localhost:8080/charon/index.html



== buildSrc module

This contains the custom, re-usable build scripts for
kotlin & spring-boot, angular, docker etc.

The only requirement is having git, java and docker in the build environment,
for ubuntu this means:

  sudo apt-get install \
    git \
    openjdk-17-jdk \
    docker \

== .github

the GitHub pipelines or workflows

* aks-deploy.yml +
  trigger a helm chart deploy from the etc/helm directory

* gradle-build.yml +
  trigger the gradle jib build for creating the images configured by the buildSrc

== etc

contains API definition, scripts, deployment descriptions, helm charts

'''


=== update UI components:

[source]
----
cd frontend
ncu -u
npm install --legacy-peer-deps
----

if UI build fail on GitHub, try deleting the caches and trigger another build

build::

npm install --legacy-peer-deps



==== Spring Auth Server Project:

https://github.com/spring-projects/spring-authorization-server +
https://www.appsdeveloperblog.com/spring-authorization-server-tutorial/ +
https://github.com/spring-projects/spring-authorization-server/issues/796 +
https://github.com/spring-projects/spring-authorization-server/issues/297 +
https://docs.spring.io/spring-authorization-server/docs/current/reference/html/guides/how-to-userinfo.html +



==== running docker without docker desktop

install with choco:

- docker-cli
- docker-compose
- use the WSL context in idea to connect to a docker deamon
- set the path do docker.exe/docker-compose.exe in idea


===== google client scope config


configure: https://console.cloud.google.com/apis/credentials/consent/edit?project=charon-394311



== Hetzner

see:
https://linuxhandbook.com/nginx-reverse-proxy-docker/
https://hub.docker.com/r/nginxproxy/acme-companion
https://linuxhandbook.com/nginx-reverse-proxy-docker/
https://github.com/nginx-proxy/nginx-proxy
https://stackoverflow.com/questions/66102225/jrcs-letsencrypt-nginx-proxy-companion-docker-image-too-many-certificates-alr
