server:
  port: 8080
  error:
    include-exception: false
    include-stacktrace: never
    whitelabel:
      enabled: false

management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    liveness-state:
      enabled: true
    readiness-state:
      enabled: true

logging:
  level:
    root: INFO

spring:
  security:
    oauth2:
      client:
        registration:
          google-idp:
            provider: google
            client-id: ${GOOGLE_CLIENT_ID:google-client-id}
            client-secret: ${GOOGLE_CLIENT_SECRET:google-client-secret}
            scope: openid, https://www.googleapis.com/auth/userinfo.profile, https://www.googleapis.com/auth/userinfo.email
            client-name: Sign in with Google
          github-idp:
            provider: github
            client-id: ${GITHUB_CLIENT_ID:github-client-id}
            client-secret: ${GITHUB_CLIENT_SECRET:github-client-secret}
            scope: user:email, read:user
            client-name: Sign in with GitHub
        provider:
          google:
            user-name-attribute: email
          github:
            user-name-attribute: login

  datasource:
    url: jdbc:h2:./charon.db
    # url: jdbc:h2:file:~/database;AUTO_SERVER=true
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

net:
  wohlfart:
    charon:
      oauth:
        data-dir: test
        issuer: "https://oauth.wired-heart.com"
        post-logout-redirect: "https://backend.wired-heart.com/charon/home"
        allowed-origins:
          - "https://backend.wired-heart.com"
          - "https://app.wired-heart.com"
        clients:
          public-client:
            client-authentication-method: NONE
            authorization-grant-type: AUTHORIZATION_CODE
            access-token-ttl: 5m
            scopes:
              - "openid"
              - "profile"
              - "email"
              - "address"
              - "phone"
              - "offline_access"
              - "message.read"
              - "message.write"
            redirect-uris:
              - "https://backend.wired-heart.com/charon/assets/silent-renew.html"
              - "https://backend.wired-heart.com/charon/silent-renew.html"
              - "https://backend.wired-heart.com/charon/home"
              - "https://app.wired-heart.com/charon/home"
            post-logout-redirect-uri: http://127.0.0.1:4200/charon/home
