server:
  port: 8080

management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    liveness-state:
      enabled: true
    readiness-state:
      enabled: true

net:
  wohlfart:
    charon:
      oauth:
        data-dir: test
        issuer: "https://oauth.wired-heart.com"
        allowed-origins:
          - "https://backend.wired-heart.com"
          - "https://app.wired-heart.com"
        redirect-uris:
          - "https://backend.wired-heart.com/charon/home"
          - "https://app.wired-heart.com/charon/home"


logging:
  level:
    root: INFO

