server:
  port: 8080

management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    liveness-state:
      enabled: true
    readiness-state:
      enabled: true

net:
  wohlfart:
    charon:
      oauth:
        data-dir: test
        issuer: "http://oauth.finalrestingheartrate.com"
        allowed-origins:
          - "http://backend.finalrestingheartrate.com"
          - "https://backend.finalrestingheartrate.com"
          - "https://oauth.finalrestingheartrate.com"
          - "https://frontend.finalrestingheartrate.com"

logging:
  level:
    root: INFO

