server:
  port: 8080
  error:
    include-exception: false
    include-stacktrace: never
    whitelabel:
      enabled: false

management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    liveness-state:
      enabled: true
    readiness-state:
      enabled: true

logging:
  level:
    root: INFO
    web: DEBUG

spring:

  datasource:
    # url: jdbc:postgresql://postgres:5432/oauth
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://charon-postgres-svc:5432/oauth}
    username: ${SPRING_DATASOURCE_USER:unconfigured-spring-datasource-user}
    password: ${SPRING_DATASOURCE_PASSWORD:unconfigured-spring-datasource-password}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 0
      maximum-pool-size: 10
      # initial 3m, we need that long to deploy postgres from scratch
      connection-timeout: 150000
      idle-timeout: 300000 #5m
      max-lifetime: 600000 #10m
      initialization-fail-timeout: -1
      validation-timeout: 1000 #1s
#
# doesn't work with the insert scripts:
  sql:
    init:
      continue-on-error: true

  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    # see: https://springjava.com/spring-boot/sending-mail-using-gmail-smtp-server-in-spring-boot
    host: ${SPRING_MAIL_HOST:unconfigured-spring-mail-host}
    port: ${SPRING_MAIL_PORT:unconfigured-spring-mail-port}
    username: ${SPRING_MAIL_USERNAME:unconfigured-spring-mail-username}
    password: ${SPRING_MAIL_PASSWORD:unconfigured-spring-mail-password}
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  freemarker:
    template-loader-path: classpath:/mail
    charset: UTF-8
    check-template-location: true
    cache: true

  security:
    oauth2:
      client:
        # see: https://github.com/spring-projects/spring-authorization-server/blob/main/samples/demo-authorizationserver/src/main/resources/templates/login.html
        #      https://console.cloud.google.com/apis/credentials
        #      for the Google client, the domain needs to be verified,
        #      https://support.google.com/a/answer/7173990?hl=en&ref_topic=4487770#zippy=%2Cim-an-advanced-usergive-me-some-technical-details
        registration:
          google-idp:
            provider: google
            client-id: ${GOOGLE_OAUTH2_CLIENT_ID:unconfigured-google-oauth2-client-id}
            client-secret: ${GOOGLE_OAUTH2_CLIENT_SECRET:unconfigured-google-oauth2-client-secret}
            scope:
              - openid
              - profile
              - email
              - https://www.googleapis.com/auth/userinfo.profile
              - https://www.googleapis.com/auth/userinfo.email
              - https://www.googleapis.com/auth/fitness.activity.read
              - https://www.googleapis.com/auth/fitness.heart_rate.read
              - https://www.googleapis.com/auth/fitness.location.read
              - https://www.googleapis.com/auth/fitness.oxygen_saturation.read
              - https://www.googleapis.com/auth/fitness.sleep.read
            # more available scopes:
            # https://www.googleapis.com/auth/fitness.body_temperature.read
            # https://www.googleapis.com/auth/fitness.location.read
            # https://www.googleapis.com/auth/fitness.sleep.read
            # https://www.googleapis.com/auth/fitness.reproductive_health.read
            # https://www.googleapis.com/auth/fitness.oxygen_saturation.read
            # https://www.googleapis.com/auth/fitness.body.read
            # https://www.googleapis.com/auth/fitness.activity.read
            # https://www.googleapis.com/auth/fitness.blood_pressure.read
            # https://www.googleapis.com/auth/fitness.nutrition.read
            # https://www.googleapis.com/auth/fitness.heart_rate.read
            # https://www.googleapis.com/auth/fitness.blood_glucose.read"
            #  "token_type": "Bearer",
            client-name: Google
        provider:
          google:
            user-name-attribute: sub
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth?access_type=offline&prompt=consent

home-url: https://backend.wired-heart.com

net:
  wohlfart:
    charon:
      api:
        base-path: "/api"
      oauth:
        data-dir: datadir
        issuer: "https://oauth.wired-heart.com"
        app-home-url: "${home-url}/charon/home"
        app-login-url: "${home-url}/charon/login"
        allowed-origins:
          - "https://oauth.wired-heart.com"
          - "${home-url}"
          - "https://app.wired-heart.com"
        # we need to re-configure all client for each app context
        # because it's a hash map
        clients:
          public-client:
            client-authentication-method: NONE
            authorization-grant-type: AUTHORIZATION_CODE
            access-token-ttl: 1m
            scopes:
              - "openid"
              - "profile"
              - "email"
              - "address"
              - "phone"
              - "offline_access"
              - "message.read"
              - "message.write"
            redirect-uris:
              - "${home-url}/charon/assets/silent-renew.html"
              - "${home-url}/charon/silent-renew.html"
              - "${home-url}/charon/home"
              - "https://app.wired-heart.com/charon/home"
            post-logout-redirect-uri: "https://app.wired-heart.com/charon/home"
          readonly-client:
            client-authentication-method: BASIC
            authorization-grant-type: CLIENT_CREDENTIALS
            client-credentials: ${READONLY_CLIENT_CREDENTIALS:unconfigured-readonly-client-credentials}
