server:
  port: 8081
  error:
    include-exception: true
    include-stacktrace: always

logging:
  level:
    root: INFO
    org:
      springframework: TRACE

spring:
  # http://localhost:8081/h2
  h2:
    console:
      enabled: true
      path: "/h2"
      settings:
        web-allow-others: true
        web-admin-password: password

net:
  wohlfart:
    charon:
      oauth:
        data-dir: test
        issuer: "http://127.0.0.1:8081"
        allowed-origins:
          - "http://127.0.0.1:4200"
        clients:
          public-client:
            client-authentication-method: NONE
            authorization-grant-type: AUTHORIZATION_CODE
            access-token-ttl: 2m
            scopes:
              - "openid"
              - "profile"
              - "email"
              - "address"
              - "phone"
              - "offline_access"
              - "message.read"
              - "message.write"
            redirect-uris:
              - "http://127.0.0.1:4200/charon/assets/silent-renew.html"
              - "http://127.0.0.1:4200/charon/silent-renew.html"
              - "http://127.0.0.1:4200/charon/home"

