server:
  port: 8081
 # servlet:
 #   context-path: "/issuer"

net:
  wohlfart:
    charon:
      oauth:
        data-dir: test
        # issuer: "http://127.0.0.1:8081"
        issuer: "http://127.0.0.1:8081"

logging:
  level:
    root: INFO
#    org.springframework.web: INFO
#    org.springframework.security: INFO
#    org.springframework.security.oauth2: INFO
#    org.springframework.boot.autoconfigure: DEBUG

