server:
  port: 8081
  error:
    include-exception: true
    include-stacktrace: always

management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    liveness-state:
      enabled: true
    readiness-state:
      enabled: true

net:
  wohlfart:
    charon:
      oauth:
        data-dir: test
        issuer: "http://127.0.0.1:8081"
        allowed-origins:
          - "http://127.0.0.1:4200"
        redirect-uris:
          - "http://127.0.0.1:4200/charon/assets/silent-renew.html"
          - "http://127.0.0.1:4200/charon/silent-renew.html"
          - "http://127.0.0.1:4200/charon/home"


logging:
  level:
    root: INFO
    org:
      springframework: TRACE
