server:
  port: 8081
  error:
    include-exception: true
    include-stacktrace: always

management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    liveness-state:
      enabled: true
    readiness-state:
      enabled: true

net:
  wohlfart:
    charon:
      oauth:
        data-dir: test
        issuer: "http://127.0.0.1:8081"
        allowed-origins:
          - "http://127.0.0.1:4200"
        client-registry:
          # the clientId not the id in the db
          - client-id: "public-client"
            client-authentication-method: NONE
            authorization-grant-type: AUTHORIZATION_CODE
            scopes:
              - "openid"
              - "profile"
              - "email"
              - "address"
              - "phone"
              - "offline_access"
              - "message.read"
              - "message.write"
            redirect-uris:
              - "http://127.0.0.1:4200/charon/assets/silent-renew.html"
              - "http://127.0.0.1:4200/charon/silent-renew.html"
              - "http://127.0.0.1:4200/charon/home"


logging:
  level:
    root: INFO
    org:
      springframework: TRACE
