server:
  port: 8080
  error:
    include-exception: false
    include-stacktrace: never
    whitelabel:
      enabled: false

management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    liveness-state:
      enabled: true
    readiness-state:
      enabled: true

logging:
  level:
    root: INFO

spring:

  datasource:
    # url: jdbc:postgresql://postgres:5432/oauth
    url: jdbc:postgresql://charon-postgres-svc:5432/oauth
    username: ${SPRING_DATASOURCE_USER:unconfigured-spring-datasource-user}
    password: ${SPRING_DATASOURCE_PASSWORD:unconfigured-spring-datasource-password}
    driverClassName: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

  mail:
    # see: https://springjava.com/spring-boot/sending-mail-using-gmail-smtp-server-in-spring-boot
    host: ${SPRING_MAIL_HOST:unconfigured-spring-mail-host}
    port: ${SPRING_MAIL_PORT:unconfigured-spring-mail-port}
    username: ${SPRING_MAIL_USERNAME:unconfigured-spring-mail-username}
    password: ${SPRING_MAIL_PASSWORD:unconfigured-spring-mail-password}
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  freemarker:
    template-loader-path: classpath:/mail
    charset: UTF-8
    check-template-location: true
    cache: true


net:
  wohlfart:
    charon:
      oauth:
        data-dir: test
        issuer: "https://oauth.wired-heart.com"
        app-home-url: "https://backend.wired-heart.com/charon/home"
        allowed-origins:
          - "https://backend.wired-heart.com"
          - "https://app.wired-heart.com"
        clients:
          public-client:
            client-authentication-method: NONE
            authorization-grant-type: AUTHORIZATION_CODE
            access-token-ttl: 5m
            scopes:
              - "openid"
              - "profile"
              - "email"
              - "address"
              - "phone"
              - "offline_access"
              - "message.read"
              - "message.write"
            redirect-uris:
              - "https://backend.wired-heart.com/charon/assets/silent-renew.html"
              - "https://backend.wired-heart.com/charon/silent-renew.html"
              - "https://backend.wired-heart.com/charon/home"
              - "https://app.wired-heart.com/charon/home"
            post-logout-redirect-uri: http://127.0.0.1:4200/charon/home
