server:
  port: 8080

management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

net:
  wohlfart:
    charon:
      oauth:
        data-dir: test
        issuer: "http://127.0.0.1:8081"

logging:
  level:
    root: INFO

