server:
  port: 8081
  servlet:
    context-path: "/issuer"

net:
  wohlfart:
    charon:
      oauth:
        data-dir: test
        issuer: "http://localhost:8081/issuer"

logging:
  level:
    root: DEBUG
#    org.springframework.web: INFO
#    org.springframework.security: INFO
#    org.springframework.security.oauth2: INFO
#    org.springframework.boot.autoconfigure: DEBUG

