
#
# kubectl delete deploy charon-deployment
# kubectl delete pods --all
# kubectl apply -f ./backend.yaml
# kubectl get pods
# kubectl get deployments
# kubectl get pods --all-namespaces
# kubectl get events
#

apiVersion: apps/v1
kind: Deployment
metadata:
  name: charon-backend-deployment
spec:
  selector:
    matchLabels:
      app: charon-backend
  replicas: 1
  template:
    metadata:
      labels:
        app: charon-backend
    spec:
      containers:
        - name: charon-backend
          image: ttl.sh/mwohlf/charon-backend
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 15
            periodSeconds: 40
            httpGet:
              path: /actuator/health/liveness
              port: 8080
          readinessProbe:
            initialDelaySeconds: 20
            periodSeconds: 30
            httpGet:
              path: /actuator/health/readiness
              port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: charon-oauth-deployment
spec:
  selector:
    matchLabels:
      app: charon-oauth
  replicas: 1
  template:
    metadata:
      labels:
        app: charon-oauth
    spec:
      containers:
        - name: charon-oauth
          image: ttl.sh/mwohlf/charon-oauth
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 15
            periodSeconds: 40
            httpGet:
              path: /actuator/health/liveness
              port: 8080
          readinessProbe:
            initialDelaySeconds: 20
            periodSeconds: 30
            httpGet:
              path: /actuator/health/readiness
              port: 8081
