apiVersion: v1
kind: Service
metadata:
  name: public-backend-svc
spec:
  type: LoadBalancer
  selector:
    app: charon-backend
  ports:
    - port: 80
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: charon-backend-deployment
spec:
  selector:
    matchLabels:
      app: charon-backend
  replicas: 1
  template:
    metadata:
      labels:
        app: charon-backend
    spec:
      containers:
        - name: charon-backend
          image: ttl.sh/mwohlf/charon-backend
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 15
            periodSeconds: 40
            httpGet:
              path: /actuator/health/liveness
              port: 8080
          readinessProbe:
            initialDelaySeconds: 20
            periodSeconds: 30
            httpGet:
              path: /actuator/health/readiness
              port: 8080


#
# see: https://kubernetes.io/docs/concepts/services-networking/_print/#defining-a-service
#
#
