
apiVersion: apps/v1
kind: Deployment
metadata:
  name: charon-backend-deployment
  namespace: development

spec:
  selector:
    matchLabels:
      app: charon-backend
  replicas: 0
  template:

    metadata:
      labels:
        app: charon-backend

    spec:
      containers:
        - name: charon-backend
          image: ttl.sh/mwohlf/charon-backend
          env:
            - name: SERVER_PORT
              value: "8080"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP

          livenessProbe:
            initialDelaySeconds: 60
            periodSeconds: 60
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 1
            httpGet:
              path: /actuator/health/liveness
              port: 8080

          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 60
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 1
            httpGet:
              path: /actuator/health/readiness
              port: 8080


---

apiVersion: v1
kind: Service
metadata:
  name: charon-backend-svc
  namespace: development
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: charon-backend
