apiVersion: apps/v1
kind: Deployment
metadata:
  name: charon-deployment
spec:
  selector:
    matchLabels:
      app: charon-backend
  replicas: 2
  template:
    metadata:
      labels:
        app: charon-backend
    spec:
      containers:
        - name: charon-backend
          image: "ttl.sh/mwohlf/charon-backend"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 15
            periodSeconds: 30
            httpGet:
              path: /actuator/health/liveness
              port: 8080
          readinessProbe:
            initialDelaySeconds: 3
            periodSeconds: 2
            httpGet:
              path: /actuator/health/readiness
              port: 8080
