
apiVersion: apps/v1
kind: Deployment
metadata:
  name: charon-hello-deployment
  namespace: development
spec:
  selector:
    matchLabels:
      app: charon-hello
  replicas: 1
  template:

    metadata:
      labels:
        app: charon-hello

    spec:
      containers:
        - name: charon-hello
          image: nginxdemos/hello
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: charon-hello-svc
  namespace: development
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: charon-hello
