
# https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/docs/tutorials/tutorial.general.md#expose-services-over-https



apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: istio
  namespace: development
spec:
  controller: istio.io/ingress-controller
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: public-charon-ig
  namespace: development
  # annotations:
  #  kubernetes.io/ingress.class: nginx
    # https://docs.microsoft.com/en-us/azure/application-gateway/
    # kubernetes.io/ingress.class: azure/application-gateway
    # appgw.ingress.kubernetes.io/appgw-ssl-certificate: "wildcard.finalrestingheartrate.com"
    # appgw.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: istio

  tls:
    - hosts:
        - backend.wired-heart.com
        - oauth.wired-heart.com
        - www.wired-heart.com
        - wired-heart.com
      secretName: wired-heart-tls

  rules:
    # http://20.22.50.219/
    # http://20.22.50.34/
    # 7fbf1b6251d84f83ae93.eastus2.aksapp.io
    # host: printhostname.7fbf1b6251d84f83ae93.eastus2.aksapp.io

  - host: backend.wired-heart.com
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: charon-backend-svc
              port:
                number: 8080

  - host: oauth.wired-heart.com
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: charon-oauth-svc
              port:
                number: 8080

  - host: www.wired-heart.com
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: charon-hello-svc
              port:
                number: 80

  - host: wired-heart.com
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: charon-hello-svc
              port:
                number: 80

  # default route
  - http:
      paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: charon-hello-svc
              port:
                number: 80

#
# 900f1cdd37f94309a139.eastus2.aksapp.io
# see: https://kubernetes.io/docs/concepts/services-networking/_print/#defining-a-service
#
