apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: charon-ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: charon-backend-service
                port:
                  number: 80

#
# https://kubernetes.io/docs/concepts/services-networking/ingress/
#  [mwohlfart1@PF3LZB4L setup]$ kubectl get svc
#  NAME                     TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)          AGE
#  charon-backend-service   NodePort    10.0.91.175   <none>        1000:32164/TCP   18m
#  kubernetes               ClusterIP   10.0.0.1      <none>        443/TCP          131m
#
# https://github.com/fbeltrao/aks-letsencrypt
