apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: public-ingress
  namespace: development
spec:
  rules:
  - host: 900f1cdd37f94309a139.eastus2.aksapp.io
    http:
      paths:

        - path: "/backend"
          pathType: Prefix
          backend:
            service:
              name: charon-backend
              port:
                number: 8080

        - path: "/oauth"
          pathType: Prefix
          backend:
            service:
              name: charon-oauth
              port:
                number: 8081

#
# 900f1cdd37f94309a139.eastus2.aksapp.io
# see: https://kubernetes.io/docs/concepts/services-networking/_print/#defining-a-service
#
