
apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: charon-ingress
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway

spec:
  rules:
  - http:
      paths:

        - path: /
          pathType: Prefix
          backend:
            service:
              name: charon-backend-svc
              port:
                number: 8080
