

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: public-charon-ig
  namespace: development
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
    # http://20.22.50.219/
    # http://20.22.50.34/
    # 7fbf1b6251d84f83ae93.eastus2.aksapp.io
    # host: printhostname.7fbf1b6251d84f83ae93.eastus2.aksapp.io

  - host: backend.finalrestingheartrate.com
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: charon-backend-svc
              port:
                number: 8080

  - host: oauth.finalrestingheartrate.com
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: charon-oauth-svc
              port:
                number: 8080

#
# 900f1cdd37f94309a139.eastus2.aksapp.io
# see: https://kubernetes.io/docs/concepts/services-networking/_print/#defining-a-service
#
