
apiVersion: apps/v1
kind: Deployment
metadata:
  name: charon-oauth-deployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: charon-oauth
  replicas: 1
  template:
    metadata:
      labels:
        app: charon-oauth
    spec:
      containers:
        - name: charon-oauth
          image: ttl.sh/mwohlf/charon-oauth
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 15
            periodSeconds: 40
            httpGet:
              path: /actuator/health/liveness
              port: 8081
          readinessProbe:
            initialDelaySeconds: 20
            periodSeconds: 30
            httpGet:
              path: /actuator/health/readiness
              port: 8081
