
apiVersion: apps/v1
kind: Deployment
metadata:
  name: charon-oauth-deployment
  namespace: development

spec:
  selector:
    matchLabels:
      app: charon-oauth
  replicas: 1
  strategy:
    type: Recreate
  template:

    metadata:
      labels:
        app: charon-oauth

    spec:
      containers:
        - name: charon-oauth
          image: ttl.sh/mwohlf/charon-oauth
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: SPRING_MAIL_HOST
              valueFrom:
                secretKeyRef:
                  name: wired-heart-secrets
                  key: spring-mail-host
            - name: SPRING_MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: wired-heart-secrets
                  key: spring-mail-username
            - name: SPRING_MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wired-heart-secrets
                  key: spring-mail-password
            - name: SPRING_MAIL_PORT
              valueFrom:
                secretKeyRef:
                  name: wired-heart-secrets
                  key: spring-mail-port
            - name: SPRING_DATASOURCE_USER
              valueFrom:
                secretKeyRef:
                  name: wired-heart-secrets
                  key: postgres-user
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wired-heart-secrets
                  key: postgres-password
            - name: GOOGLE_OAUTH2_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: wired-heart-secrets
                  key: google-oauth2-client-id
            - name: GOOGLE_OAUTH2_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: wired-heart-secrets
                  key: google-oauth2-client-secret
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP

          livenessProbe:
            # we have to wait for the db
            initialDelaySeconds: 100
            periodSeconds: 60
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 1
            httpGet:
              path: /actuator/health/liveness
              port: 8080

          readinessProbe:
            # we have to wait for the db
            initialDelaySeconds: 100
            periodSeconds: 60
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 1
            httpGet:
              path: /actuator/health/readiness
              port: 8080


---

apiVersion: v1
kind: Service
metadata:
  name: charon-oauth-svc
  namespace: development
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: charon-oauth
