
apiVersion: apps/v1
kind: Deployment
metadata:
  name: charon-oauth-deployment
  namespace: development
spec:
  selector:
    matchLabels:
      app: charon-oauth
  replicas: 1
  template:
    metadata:
      labels:
        app: charon-oauth
    spec:

      containers:
        - name: charon-oauth
          image: ttl.sh/mwohlf/charon-oauth
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP

          livenessProbe:
            initialDelaySeconds: 60
            periodSeconds: 60
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 1
            httpGet:
              path: /actuator/health/liveness
              port: 8081

          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 60
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 1
            httpGet:
              path: /actuator/health/readiness
              port: 8081
