apiVersion: v1
kind: Secret
metadata:
  # used in the ingres config to lookup the cert keys
  name: wired-heart-tls
  namespace: development

data:
  tls.crt: {{ .Values.tls.crt }}
  tls.key: {{ .Values.tls.key }}

type: kubernetes.io/tls


#
# this is just the layout for the Secret used by ingress
# the file is generated before deployment by the manage-certs.bash script
#
