#
# see: https://kubernetes.io/docs/concepts/services-networking/_print/#defining-a-service
#
apiVersion: v1
kind: Service
metadata:
  name: public-charon-svc
spec:
  # Exposes the Service externally using a cloud provider's load balancer.
  # NodePort and ClusterIP Services, to which the external load balancer routes, are automatically created.
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: charon-backend
  ports:
    - port: 80
      targetPort: 8080
