openapi: 3.0.1
info:
  description: charon POC
  version: 0.0.1
  title: OpenAPI for Charon
  license:
    name: Apache-2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: build
    description: Build Infos
paths:

  /build-properties:
    get:
      tags:
        - build
      operationId: readBuildProperties
      description: ''
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BuildProperties'
        '405':
          description: Invalid input

components:
  schemas:
    BuildProperties:
      required:
        - date
        - version
      type: object
      properties:
        date:
          type: string
        version:
          type: string
