version: "3.8"

# to set up docker in intellij without docker desktop,
# install ubuntu with docker in WSL2,
#  then "File" -> "Settings" -> "Build, Execution, .." -> "Docker"  -> WSL2 -> "Ubuntu"

services:

  postgres:
    image: postgres:15.3-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: sa
      # if the DB doesn't get created try to delete the image and start again
      POSTGRES_DB: oauth
      # usually at /var/lib/postgresql/data
      # this configures our own directory for data:
      PGDATA: /data/postgres/oauthdb
    volumes:
      - postgres-data:/data/postgres

volumes:
  postgres-data:

