version: "3.8"

#  this file contains the backend services needed for development

services:

  postgres:
    image: postgres:15.2-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: sa
      # if the DB doesn't get created try to delete the image and start again
      POSTGRES_DB: oauth
      # usually at /var/lib/postgresql/data
      # this configures our own directory for data:
      PGDATA: /data/postgres
    volumes:
      - postgres-data:/data/postgres

  mongo:
    # image: mongo:4.4.0
    image: mongo:4.0.22
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=somepass
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express:0.54.0
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=somepass

  redis:
    image: redis:7.0.10
    # command: redis-server --requirepass somepass
    # to connect in redis-insight
    #    host: redis
    #    port: 6379
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  redis-insight:
    image: redislabs/redisinsight
    ports:
      - "8001:8001"
    volumes:
      - redis-insight-data:/db

  # this is for testing and development and serves the custom element module directory on port 8085
  # you get the index page at http://localhost:8085/guided-tests/
  webserver:
    image: httpd:2.4.35
    ports:
      - "8085:80"
    # volumes:
    #   - ../GuidedTestsComponent/:/usr/local/apache2/htdocs/
#
#  docker run \
#     --name webserver \
#      -p 8085:80 \
#      -v "GuidedTestsComponent/:/usr/local/apache2/htdocs/" \
#      httpd:2.4.35
#

volumes:
  postgres-data:
  mongo-data:
  redis-data:
  redis-insight-data:
