
### GET request with a header
GET http://localhost:8081/oauth2/authorize?client_id=public-client&redirect_uri=http%3A%2F%2F127.0.0.1%3A4200%2Fcharon%2Fassets%2Fsilent-renew.html&response_type=code&scope=openid%20profile%20email%20offline_access&nonce=e7ccf2a5584f1a1c31f3277986a2d74090SWi9pCm&state=5fe0d927b8f32cccdf894241169694448c7ejf7yv&code_challenge=YlH0L4j27DwRaPfwrWUfAPOeq_usAbNnVw6ZD3eq6yE&code_challenge_method=S256&prompt=none
