

###
# @name 001
GET http://127.0.0.1:8081/oauth2/authorize?client_id=public-client&redirect_uri=http%3A%2F%2F127.0.0.1%3A4200%2Fcharon%2Fhome&response_type=code&scope=openid%20profile%20email%20offline_access&nonce=fa28c6285576ae766af8c760f9eb85aa1dxFj0ILy&state=b8d41a63a27d84a59758a0d5b00a86a1a1sFq1qxm&code_challenge=mUgKohr3Fhm-G-OMJ-8ulYLd5AUZpZnQAU5CLdGw0a4&code_challenge_method=S256
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Accept-Language: en-US,en;q=0.9,de-DE;q=0.8,de;q=0.7,fr-FR;q=0.6,fr;q=0.5
Cache-Control: no-cache
Connection: keep-alive
Pragma: no-cache
Referer: http://127.0.0.1:4200/
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36

> {%
   client.global.set("csrf", response.body.match("value=\".*\"")[0].trim().substring("value=\"".length).slice(0, -1))
   client.log("csrf: " + client.global.get("csrf"));
%}

###
# @name 002
POST http://127.0.0.1:8081/login
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Accept-Language: en-US,en;q=0.9,de-DE;q=0.8,de;q=0.7,fr-FR;q=0.6,fr;q=0.5
Cache-Control: no-cache
Connection: keep-alive
Origin: http://127.0.0.1:8081
Pragma: no-cache
Referer: http://127.0.0.1:8081/login
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
Content-Type: application/x-www-form-urlencoded

_csrf={{csrf}}&username=user&password=pass
> {%
  // we should be logged in here and have a cookie
%}

###

# curl 'http://127.0.0.1:8081/oauth2/token'
#  -H 'Accept: application/json, text/plain, */*'
#  -H 'Accept-Language: en-US,en;q=0.9,de-DE;q=0.8,de;q=0.7,fr-FR;q=0.6,fr;q=0.5'
#  -H 'Cache-Control: no-cache'
#  -H 'Connection: keep-alive'
#  -H 'Content-Type: application/x-www-form-urlencoded'
#  -H 'DNT: 1'
#  -H 'Origin: http://127.0.0.1:4200'
#  -H 'Pragma: no-cache'
#  -H 'Referer: http://127.0.0.1:4200/'
#  -H 'Sec-Fetch-Dest: empty'
#  -H 'Sec-Fetch-Mode: cors'
#  -H 'Sec-Fetch-Site: same-site'
#  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36'
#  -H 'sec-ch-ua: "Google Chrome";v="105", "Not)A;Brand";v="8", "Chromium";v="105"'
#  -H 'sec-ch-ua-mobile: ?0'
#  -H 'sec-ch-ua-platform: "Windows"'
#  --data-raw 'grant_type=authorization_code&client_id=public-client&code_verifier=75c991159a37af81861d1d738ffca818c08a3dba428cb9830952fd57a2c2wYwhypk&code=5_3h8IsrlLvXCSFL259661HFawTO4N6IpGrvYy-mhrjua5Eg72kte-h408y9DtCktD96oP4ijMDxTP1doRkN4HrBdMGbdsu-A39Un6kN1S_6c6wcWkI5mHrYCt3hepmf&redirect_uri=http%3A%2F%2F127.0.0.1%3A4200%2Fcharon%2Fhome'
#  --compressed
POST http://127.0.0.1:8081/oauth2/token
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.9,de-DE;q=0.8,de;q=0.7,fr-FR;q=0.6,fr;q=0.5
Cache-Control: no-cache
Connection: keep-alive
Origin: http://127.0.0.1:4200
Pragma: no-cache
Referer: http://127.0.0.1:4200/
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
Content-Type: application/x-www-form-urlencoded

grant_type=authorization_code&client_id=public-client&code_verifier=75c991159a37af81861d1d738ffca818c08a3dba428cb9830952fd57a2c2wYwhypk&code=5_3h8IsrlLvXCSFL259661HFawTO4N6IpGrvYy-mhrjua5Eg72kte-h408y9DtCktD96oP4ijMDxTP1doRkN4HrBdMGbdsu-A39Un6kN1S_6c6wcWkI5mHrYCt3hepmf&redirect_uri=http%3A%2F%2F127.0.0.1%3A4200%2Fcharon%2Fhome

###

