
###
GET http://localhost:8081/issuer/.well-known/openid-configuration

{
  "issuer": "http://localhost:4200/issuer",
  "authorization_endpoint": "http://localhost:4200/issuer/oauth2/authorize",
  "token_endpoint": "http://localhost:4200/issuer/oauth2/token",
  "token_endpoint_auth_methods_supported": [
    "client_secret_basic",
    "client_secret_post",
    "client_secret_jwt",
    "private_key_jwt"
  ],
  "jwks_uri": "http://localhost:4200/issuer/oauth2/jwks",
  "userinfo_endpoint": "http://localhost:4200/issuer/userinfo",
  "response_types_supported": [
    "code"
  ],
  "grant_types_supported": [
    "authorization_code",
    "client_credentials",
    "refresh_token"
  ],
  "revocation_endpoint": "http://localhost:4200/issuer/oauth2/revoke",
  "revocation_endpoint_auth_methods_supported": [
    "client_secret_basic",
    "client_secret_post",
    "client_secret_jwt",
    "private_key_jwt"
  ],
  "introspection_endpoint": "http://localhost:4200/issuer/oauth2/introspect",
  "introspection_endpoint_auth_methods_supported": [
    "client_secret_basic",
    "client_secret_post",
    "client_secret_jwt",
    "private_key_jwt"
  ],
  "subject_types_supported": [
    "public"
  ],
  "id_token_signing_alg_values_supported": [
    "RS256"
  ],
  "scopes_supported": [
    "openid"
  ]
}

###
GET http://localhost:8081/.well-known/oauth-authorization-server

###
GET http://localhost:8081/login

> {%
   client.log(response.body.toLowerCase());

%}

###
POST http://localhost:8081/login
Content-Type: application/x-www-form-urlencoded

username=user1&password=s3cr37&_csrf=45e0170d-5840-42c9-b1a3-abf794f948b7



------------------

request/log sequence:

*** Navigated to http://localhost:4200/charon/index.html
// dummy config endpoint:
zone.js:2680 XHR failed loading: GET "http://localhost:4200/api/client-config-todo".

not working:
Received [GET /.well-known/openid-configuration HTTP/1.1


*** Navigated to http://localhost:8081/oauth2/authorize?client_id=messaging-client&redirect_uri=http%3A%2F%2Flocalhost%3A4200&response_type=code&scope=message.read&nonce=98d71f406a75d8148012dbb062b0a4cf04TPgMH8v&state=bc56c51092672cb35097d4b8d9e0d60932qME5xzJ&code_challenge=MtNr2wT1UJvNzkVHDx0AGAWEU9-361gbGitCFpEjbuE&code_challenge_method=S256

http://localhost:8081/oauth2/authorize?client_id=messaging-client&redirect_uri=http://localhost:4200&response_type=code&scope=message.read&nonce=1c623a6ed19714832d118b3727d0fa6389LDAdLth&state=bc56c51092672cb35097d4b8d9e0d60932qME5xzJ&code_challenge=xoAvvY080Etirb0U1BqF_IGz9nN3XPxGP1t0nFbN57k&code_challenge_method=S256


http://localhost:4200/issuer/oauth2/authorize?client_id=messaging-client&redirect_uri=http://localhost:4200&response_type=code&scope=message.read&nonce=cf8f865c7c71bb078c598add8b7625fb24jEgCpMu&state=9a765564882d1feefe8d897ef7203c6cc8zWsavK0&code_challenge=2rSciFtY6Y_KeTtmlR-p6jq-kkgZiIcuGbZwrQb8gh8&code_challenge_method=S256



flow:

* get config
http://localhost:4200/issuer/.well-known/openid-configuration

* create nonce
* request with clientId, redirectUrl response_type, ...
http://localhost:4200/issuer/oauth2/authorize?client_id=messaging-client&redirect_uri=http://localhost:4200&response_type=code&scope=message.read&nonce=5cd4eed9f336e1b1b4fb235646fa8586dfDij1QVb&state=2d14493e54095e15e3c0a39b66fb7a7a14CzCFNoL&code_challenge=r_7KwlyZilvOlSjievzhfpRWNGlkksAHoTtdm7Tn3g8&code_challenge_method=S256

* redirect location to login:  user1/s3cr37
http://localhost:4200/issuer/login

* post login data
* reedirect to error page
http://localhost:4200/issuer/error?client_id=messaging-client&redirect_uri=http://localhost:4200&response_type=code&scope=message.read&nonce=5cd4eed9f336e1b1b4fb235646fa8586dfDij1QVb&state=2d14493e54095e15e3c0a39b66fb7a7a14CzCFNoL&code_challenge=r_7KwlyZilvOlSjievzhfpRWNGlkksAHoTtdm7Tn3g8&code_challenge_method=S256
