# Default values
# see: https://josephrodriguezg.medium.com/deploying-a-spring-boot-application-in-kubernetes-using-helm-charts-5c04c2d46e16
replicaCount: 1
image:
  repository: ghcr.io
  tag: charon-backend:latest
  pullPolicy: IfNotPresent

service:
  name: nginx
  type: NodePort
  externalPort: 8080
  internalPort: 8080

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  hosts:
    - chart-example.local
      paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: springboot-starterkit-svc
              servicePort: 80
