openapi: 3.0.0
info:
  description: Petshop to test yml file generation
  version: 1.0.0
  title: Petshop example

paths:
  /petshop: # That will be the name of the api -> PetshopApi
    post: # Type of request: POST
      tags:
        - shop
      summary: Do nothing really
      description: ''
      operationId: petshopMethod # That will be the method to add the logic
      responses: # ApiResponse documentation
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
        '405':
          description: Invalid input
      requestBody: # RequestBody for the Post request
        $ref: '#/components/requestBodies/Pet'
