openapi: 3.0.1
info:
  description: charon POC
  version: 0.0.1
  title: OpenAPI for Charon
  license:
    name: Apache-2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'

paths:

  /configuration-details:
    $ref: "./endpoints/configuration-details.yaml"

  /client-configuration-list:
    $ref: "./endpoints/client-configuration-list.yaml"

  /random-data:
    $ref: "./endpoints/random-data.yaml"

  /fitness-data:
    $ref: "./endpoints/fitness-data-list.yaml"

  /fitness-data/{id}:
    $ref: "./endpoints/fitness-data-item.yaml"

  /logs: # used by UI logger, hardcoded
    $ref: "./endpoints/logging.yaml"

components:
  schemas:
    AccessToken: # data from oauth server resource endpoint, we use a webclient
      $ref: "./model/AccessToken.yaml"
