openapi: 3.0.1
info:
  description: charon POC
  version: 0.0.1
  title: OpenAPI for Charon
  license:
    name: Apache-2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'


tags:
  - name: configurationDetails
    description: Configuration Details
  - name: loggingBackend
    description: Logging Backend
  - name: dataAccess
    description: Data Backend


paths:

  /configuration-details:
    $ref: "./endpoints/configuration-details.yaml"

  /client-configuration-list:
    $ref: "./endpoints/client-configuration-list.yaml"

  /random-data:
    $ref: "./endpoints/random-data.yaml"

  /fit-data-sources:
    $ref: "./endpoints/fit-data-sources.yaml"

  /logs: # used by UI logger, hardcoded
    $ref: "./endpoints/logging.yaml"

components:
  schemas:
    AccessToken: # data from oauth server resource endpoint, we use a webclient
      $ref: "./model/AccessToken.yaml"
