openapi: 3.0.1
info:
  description: charon POC
  version: 0.0.1
  title: OpenAPI for Charon
  license:
    name: Apache-2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'

paths:

  /configuration-details:
    $ref: "./endpoints/configuration-details.yaml"

  /access-token/{xid}:
    $ref: "./endpoints/access-token.yaml"
