
management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    liveness-state:
      enabled: true
    readiness-state:
      enabled: true

net:
  wohlfart:
    charon:
      data-dir: "test"
      webjar-base: "/charon"
      api:
        base-path: "/api"     # this is prefix in all controller
        logging: "/logging"       # post endpoint for nxg logging
        oauth: "/oauth"         # oauth resources endpoint
      oauth-clients:
        - config-id: spring-oauth
          issuer-uri: http://127.0.0.1:8081
          client-id: public-client
        - config-id: google
          issuer-uri: http://google.finalrestingheartrate.com/
          client-id: public-google-client
