
logging:
  level:
    root: INFO
    org:
      springframework: debug

net:
  wohlfart:
    charon:
      data-dir: "test"
      webjar-base: "/charon"
      api:
        base-path: "/api"      # this is prefix in all controller
        logging: "/logs"       # post endpoint for nxg logging
        oauth: "/oauth"        # oauth resources endpoint
      oauth-clients:
        - config-id: google
          issuer-uri: https://accounts.google.com
          client-id: 246987228084-su5371btnpjd9ptjrqosid9lf8crq72p.apps.googleusercontent.com
        - config-id: spring-oauth
          issuer-uri: http://127.0.0.1:8081
          client-id: public-client
          post-logout-redirect-uri: http://127.0.0.1:8081/logout

