#
# the ConfigurationDetails data type
#
type: object
required:
  - configId
  - issuerUri
  - clientId
properties:
  configId:
    example: "simpleConfig"
    type: string
  issuerUri:
    example: "http://somewhere/to/find"
    type: string
  clientId:
    example: "simpleClient"
    type: string
  postLogoutRedirectUri:
    example: "http://somewhere/logout"
    type: string
