#
# the ConfigurationDetails data type
#
type: object
required:
  - configId
  - config
properties:
  configId:
    example: "simpleConfig"
    type: string
  config:
    type: object
    additionalProperties:
      type: object
