#
# the ConfigurationDetails data type
#
type: object
required:
  - name
  - version
  - timestamp
  - logging
  - oauth
properties:
  name:
    example: "charon"
    type: string
  version:
    example: "0.0.1-SNAPSHOT"
    type: string
  timestamp:
    example: "1995-09-07T10:40:52Z"
    format: date-time
    type: string
  logging:
    example: "some/where/to/find"
    type: string
