name: aks-deploy

# see: https://github.com/Azure/actions-workflow-samples/blob/master/Kubernetes/build-and-deploy-docker-image-to-aks-using-helm.yml

on:
  workflow_dispatch:

env:
  CLUSTER: charonCluster
  RESOURCE_GROUP: charonResourceGroup
  NAMESPACE: test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_SP_CREDENTIALS}}

#      # Container build and push to a Azure Container registry (ACR)
#      - run: |
#          docker build . -t ${{ env.REGISTRY_NAME }}.azurecr.io/myimage:${{ github.sha }}
#          docker push ${{ env.REGISTRY_NAME }}.azurecr.io/myimage:${{ github.sha }}

      # Set the target Azure Kubernetes Service (AKS) cluster.
      - uses: azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_SP_CREDENTIALS }}
          cluster-name: ${{ env.CLUSTER }}
          resource-group: ${{ env.RESOURCE_GROUP }}

      # Create namespace if doesn't exist
      - run: |
          kubectl create namespace ${{ env.NAMESPACE }} --dry-run -o json | kubectl apply -f -

      # Baking the helm chart to generate the manifests to deploy
      - uses: azure/k8s-bake@v2.2
        with:
          silent: 'false' # set this to get more verbose helm command logs
          renderEngine: 'helm2'
          helmChart: '${{ github.workspace }}/etc/helm/'
          # helm-version: 'latest'
        id: bake

      - name: Authenticate to the docker registry
        uses: docker/login-action@v2
        with:
          # registry: registry.gitlab.com
          registry: ghcr.io
          username: mwohlf
          password: ${{ secrets.GHCR_TOKEN }}

      # Deploy app to AKS
      - uses: azure/k8s-deploy@v1
        with:
          manifests: ${{ steps.bake.outputs.manifestsBundle }}
          images: |
            ghcr.io/charon-backend:latest
          namespace: ${{ env.NAMESPACE }}
