name: az-deploy
on:
  push:
    branches:
      - 'main'

# see: https://tomgregory.com/build-gradle-projects-with-github-actions/#:~:text=If%20you%20have%20a%20Gradle,entirely%20hosted%20on%20their%20infrastructure

jobs:

  az-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout sources
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
          cache: gradle

      #
      # this creates the docker images we need for the services
      - name: Run gradle jib to create and push the image to ttl
        run: ./gradlew jib --no-daemon

      # set and authorize to the target Azure Kubernetes Service (AKS) cluster.
      - uses: azure/aks-set-context@v1
        with:
          creds: "${{ secret.AZURE_SP_CREDENTIALS }}"
          cluster-name: charonCluster
          resource-group: charonResourceGroup

      - name: Deploy the image setup as helm chart
        uses: Azure/k8s-deploy@v1
        with:
          manifests: |
            manifests/deployment.yaml
            manifests/service.yaml
          images: |
            cloudlifeacr.azurecr.io/k8sflask:${{ github.sha }}
