name: gradle-build

# creating the images and pushing them into the repository

on:
  push:
    branches:
      - 'develop'
  #   - 'main'
  workflow_dispatch:

# only run one instance
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

env:
  WEBHOOK_URL : ${{ secrets.WEBHOOK_URL }}
  WEBHOOK_SECRET : ${{ secrets.WEBHOOK_SECRET }}



jobs:

  gradle-build:
    name: build the images with the jib gradle task
    runs-on: ubuntu-22.04

    steps:

      - uses: actions/checkout@v3.3.0
      - uses: actions/setup-java@v3.9.0
        with:
          java-version: 17
          distribution: 'adopt'
          cache: gradle

      - name: Run gradle build jib
        id: run-gradle-build-jib
        uses: gradle/gradle-build-action@v2.3.3
        with:
          gradle-executable: ${{ github.workspace }}/gradlew
          arguments: |
            build jib
            --no-daemon
            --scan

      # needed for the postgres image
      - name: Run gradle build backends
        id: run-gradle-build-backends
        uses: gradle/gradle-build-action@v2.3.3
        with:
          gradle-executable: ${{ github.workspace }}/gradlew
          arguments: |
            build backends
            --no-daemon
            --scan

      # call the deployment scrip
      - name: Invoke deployment hook
        id: trigger-deployment
        uses: distributhor/workflow-webhook@v3.0.7
        with:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
          data: '{ "action": "redeploy" }'
          verbose: true
          max_time: 3
