name: gradle-build
on:
  push:
    branches:
      - 'develop'
      - 'master'

jobs:

  gradle-build:
    runs-on: ubuntu-latest
    steps:

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
          cache: gradle

      - name: Checkout the sourcecode
        uses: actions/checkout@v2

        # for historical reasons
      - name: Run gradle build to compile the applications
        run: ./gradlew build --no-daemon

      - name: Authenticate to the docker registry
        uses: docker/login-action@v2
        with:
          # registry: registry.gitlab.com
          registry: ghcr.io
          username: ${{ secrets.GHCR_TOKEN }}

      # this creates and pushes the docker images we need for the services
      - name: Run gradle jib to create and push the image
        run: ${{ github.workspace }}/gradlew jib --no-daemon


