name: gradle-build
on:
  push:
    branches:
      - 'develop'
      - 'main'

jobs:

  gradle-build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
      - name: Set up JDK 17, Checkout the sourcecode
        with:
          java-version: 17
          distribution: 'adopt'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

        # for historical reasons
      - name: Run gradle build to compile the applications
        run: ${{ github.workspace }}/gradlew build --no-daemon

      - name: Authenticate to the docker registry
        uses: docker/login-action@v2
        with:
          # registry: registry.gitlab.com
          registry: ghcr.io
          username: ${{ secrets.GHCR_TOKEN }}

      # this creates and pushes the docker images we need for the services
      - name: Run gradle jib to create and push the image
        run: ${{ github.workspace }}/gradlew jib --no-daemon


