name: gradle-build

# creating the images and pushing them into the repository

on:
  push:
    branches:
      - 'develop'
  #   - 'main'
  workflow_dispatch:

# only run one instance
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

env:
  HPASSWORD : ${{ secrets.HPASSWORD }}



jobs:

  gradle-build:
    name: build the images with the jib gradle task
    runs-on: ubuntu-22.04

    steps:

      - uses: actions/checkout@v3.3.0
      - uses: actions/setup-java@v3.9.0
        with:
          java-version: 17
          distribution: 'adopt'
          cache: gradle

      - name: Run gradle build jib
        id: run-gradle-build-jib
        uses: gradle/gradle-build-action@v2.3.3
        with:
          gradle-executable: ${{ github.workspace }}/gradlew
          arguments: |
            build jib
            --no-daemon
            --scan
