name: gradle-build

# creating the images and pushing them into the repository

on:
  push:
    branches:
      - 'develop'
  #   - 'main'
  workflow_dispatch:

jobs:

  gradle-build:
    name: build the images with the jib gradle task
    id: build-job
    runs-on: ubuntu-22.04

    steps:

      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
          cache: gradle

      - name: Setup Gradle
        id: setup-gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build --scan

      - name: Run gradle build to compile the applications
        id: run-build
        run: ${{ github.workspace }}/gradlew build --no-daemon --scan

      # this creates and pushes the docker images we need for the services
      - name: Run gradle jib to create and push the images
        id: run-jib
        run: ${{ github.workspace }}/gradlew jib --no-daemon

