name: gradle-build
on:
  push:
    branches:
      - 'develop'
      - 'main'

jobs:

  gradle-build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
          cache: gradle
