name: gradle-build

# creating the images and pushing them into the repository

on:
  workflow_dispatch:

#  push:
#    branches:
#      - 'develop'
#      - 'main'

jobs:

  gradle-build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run gradle build to compile the applications
        run: ${{ github.workspace }}/gradlew build --no-daemon

      - name: Authenticate to the docker registry
        uses: docker/login-action@v2
        with:
          # registry: registry.gitlab.com
          registry: ghcr.io
          username: mwohlf
          password: ${{ secrets.GHCR_TOKEN }}

      # this creates and pushes the docker images we need for the services
      - name: Run gradle jib to create and push the image
        run: ${{ github.workspace }}/gradlew jib --no-daemon

