name: CI
on: [push]

# see: https://tomgregory.com/build-gradle-projects-with-github-actions/#:~:text=If%20you%20have%20a%20Gradle,entirely%20hosted%20on%20their%20infrastructure

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
          cache: gradle
        # for historical reasons
      - name: Run gradle build to compile the applications
        run: ./gradlew build --no-daemon
        # jib probably depends on build anyways
      - name: Run gradle jib to create the image
        run: ./gradlew jib --no-daemon

