name: gradle-build

# creating the images and pushing them into the repository

on:
  push:
    branches:
      - 'develop'
  #   - 'main'
  workflow_dispatch:

jobs:

  gradle-build:
    name: build the images with the jib gradle task
    runs-on: ubuntu-22.04

    steps:

      - uses: actions/checkout@main
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
          cache: gradle

      - name: Run gradle
        id: run-gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-executable: ${{ github.workspace }}/gradlew
          arguments: |
            build jib
            --no-daemon
            --scan

