name: gradle-build
on:
  push:
    branches:
      - 'develop'

jobs:

  gradle-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
          cache: gradle
        # for historical reasons
      - name: Run gradle build to compile the applications
        run: ./gradlew build --no-daemon

