name: renew-certs

# Controls when the workflow will run
on:
  # # once a month
  # schedule:
  #  - cron:  '0 5 */31 * *'
  # # manually from the Actions tab
  workflow_dispatch:

env:
  # reading the env from the GitHub action secrets
  # the values are used in the script
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  # this is used to encrypt the file that will contain the TSL keys created by the certbot
  GPG_PASSPHRASE : ${{ secrets.GPG_PASSPHRASE }}


jobs:

  refresh-certs:
    name: refresh certs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_SP_CREDENTIALS}}

      - name: Setup git config
        run: |
          # setup git username and email for the push
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Run the manage-certs script
        run: |
          bash ${{ github.workspace }}/etc/certs/manage-certs.bash create_cert

      - name: Stage and push the encrypted keys
        run: |
          echo "running on branch ${GITHUB_REF##*/}"
          git add ${{ github.workspace }}/etc/certs/tls.crt.bin
          git add ${{ github.workspace }}/etc/certs/tls.key.bin
          git commit -m "added certs"
          git push origin ${GITHUB_REF##*/}
