name: renew-certs

# Controls when the workflow will run
on:
  # # once a month
  # schedule:
  #  - cron:  '0 5 */31 * *'
  # # manually from the Actions tab
  workflow_dispatch:

env:
  # reading the env from the GitHub action secrets
  # the values are used in the script
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  # this is used to encrypt the file that will contain the TSL keys created by the certbot
  GPG_PASSPHRASE : ${{ secrets.GPG_PASSPHRASE }}


jobs:

  refresh-certs:
    name: refresh certs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_SP_CREDENTIALS}}

      - name: Run the script
        run: bash ${{ github.workspace }}/etc/certs/renew-certs.bash
